//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.31 at 02:59:35 PM CET 
//


package com.example.xml.team3.model.grades;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.xml.team3.model.grades package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.xml.team3.model.grades
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Grades }
     * 
     */
    public Grades createGrades() {
        return new Grades();
    }

    /**
     * Create an instance of {@link Grades.Uniqueness }
     * 
     */
    public Grades.Uniqueness createGradesUniqueness() {
        return new Grades.Uniqueness();
    }

    /**
     * Create an instance of {@link Grades.Keywords }
     * 
     */
    public Grades.Keywords createGradesKeywords() {
        return new Grades.Keywords();
    }

    /**
     * Create an instance of {@link Grades.Abstract }
     * 
     */
    public Grades.Abstract createGradesAbstract() {
        return new Grades.Abstract();
    }

    /**
     * Create an instance of {@link Grades.Conclusions }
     * 
     */
    public Grades.Conclusions createGradesConclusions() {
        return new Grades.Conclusions();
    }

    /**
     * Create an instance of {@link Grades.Experiments }
     * 
     */
    public Grades.Experiments createGradesExperiments() {
        return new Grades.Experiments();
    }

    /**
     * Create an instance of {@link Grades.Layout }
     * 
     */
    public Grades.Layout createGradesLayout() {
        return new Grades.Layout();
    }

    /**
     * Create an instance of {@link Grades.Formality }
     * 
     */
    public Grades.Formality createGradesFormality() {
        return new Grades.Formality();
    }

    /**
     * Create an instance of {@link Grades.GeneralGrade }
     * 
     */
    public Grades.GeneralGrade createGradesGeneralGrade() {
        return new Grades.GeneralGrade();
    }

    /**
     * Create an instance of {@link Grades.Images }
     * 
     */
    public Grades.Images createGradesImages() {
        return new Grades.Images();
    }

    /**
     * Create an instance of {@link Grades.References }
     * 
     */
    public Grades.References createGradesReferences() {
        return new Grades.References();
    }

    /**
     * Create an instance of {@link Grades.CanBePublished }
     * 
     */
    public Grades.CanBePublished createGradesCanBePublished() {
        return new Grades.CanBePublished();
    }

    /**
     * Create an instance of {@link Grades.Headings }
     * 
     */
    public Grades.Headings createGradesHeadings() {
        return new Grades.Headings();
    }

}
