//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.03 at 05:11:22 PM CET 
//


package com.example.xml.team3.model.review;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="grades">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="uniqueness" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                   &lt;element name="keywords" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                   &lt;element name="abstract" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                   &lt;element name="conclusions" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                   &lt;element name="experiments" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                   &lt;element name="layout" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                   &lt;element name="formality" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                   &lt;element name="generalGrade" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                   &lt;element name="references" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                   &lt;element name="headings" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="comments" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="refId" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="workflowId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="summaryComment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "grades",
    "comments",
    "workflowId",
    "summaryComment"
})
@XmlRootElement(name = "review")
public class Review {

    @XmlElement(required = true)
    protected Review.Grades grades;
    @XmlElement(required = true)
    protected List<Review.Comments> comments;
    @XmlElement(required = true)
    protected String workflowId;
    @XmlElement(required = true)
    protected String summaryComment;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the grades property.
     * 
     * @return
     *     possible object is
     *     {@link Review.Grades }
     *     
     */
    public Review.Grades getGrades() {
        return grades;
    }

    /**
     * Sets the value of the grades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Review.Grades }
     *     
     */
    public void setGrades(Review.Grades value) {
        this.grades = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Review.Comments }
     * 
     * 
     */
    public List<Review.Comments> getComments() {
        if (comments == null) {
            comments = new ArrayList<Review.Comments>();
        }
        return this.comments;
    }

    /**
     * Gets the value of the workflowId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowId() {
        return workflowId;
    }

    /**
     * Sets the value of the workflowId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowId(String value) {
        this.workflowId = value;
    }

    /**
     * Gets the value of the summaryComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryComment() {
        return summaryComment;
    }

    /**
     * Sets the value of the summaryComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryComment(String value) {
        this.summaryComment = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="refId" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Comments {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "refId")
        @XmlSchemaType(name = "anySimpleType")
        protected String refId;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the refId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRefId() {
            return refId;
        }

        /**
         * Sets the value of the refId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRefId(String value) {
            this.refId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="uniqueness" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *         &lt;element name="keywords" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *         &lt;element name="abstract" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *         &lt;element name="conclusions" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *         &lt;element name="experiments" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *         &lt;element name="layout" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *         &lt;element name="formality" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *         &lt;element name="generalGrade" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *         &lt;element name="references" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *         &lt;element name="headings" type="{http://ftn.uns.ac.rs/team3/review}grade"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uniqueness",
        "keywords",
        "_abstract",
        "conclusions",
        "experiments",
        "layout",
        "formality",
        "generalGrade",
        "references",
        "headings"
    })
    public static class Grades {

        protected int uniqueness;
        protected int keywords;
        @XmlElement(name = "abstract")
        protected int _abstract;
        protected int conclusions;
        protected int experiments;
        protected int layout;
        protected int formality;
        protected int generalGrade;
        protected int references;
        protected int headings;

        /**
         * Gets the value of the uniqueness property.
         * 
         */
        public int getUniqueness() {
            return uniqueness;
        }

        /**
         * Sets the value of the uniqueness property.
         * 
         */
        public void setUniqueness(int value) {
            this.uniqueness = value;
        }

        /**
         * Gets the value of the keywords property.
         * 
         */
        public int getKeywords() {
            return keywords;
        }

        /**
         * Sets the value of the keywords property.
         * 
         */
        public void setKeywords(int value) {
            this.keywords = value;
        }

        /**
         * Gets the value of the abstract property.
         * 
         */
        public int getAbstract() {
            return _abstract;
        }

        /**
         * Sets the value of the abstract property.
         * 
         */
        public void setAbstract(int value) {
            this._abstract = value;
        }

        /**
         * Gets the value of the conclusions property.
         * 
         */
        public int getConclusions() {
            return conclusions;
        }

        /**
         * Sets the value of the conclusions property.
         * 
         */
        public void setConclusions(int value) {
            this.conclusions = value;
        }

        /**
         * Gets the value of the experiments property.
         * 
         */
        public int getExperiments() {
            return experiments;
        }

        /**
         * Sets the value of the experiments property.
         * 
         */
        public void setExperiments(int value) {
            this.experiments = value;
        }

        /**
         * Gets the value of the layout property.
         * 
         */
        public int getLayout() {
            return layout;
        }

        /**
         * Sets the value of the layout property.
         * 
         */
        public void setLayout(int value) {
            this.layout = value;
        }

        /**
         * Gets the value of the formality property.
         * 
         */
        public int getFormality() {
            return formality;
        }

        /**
         * Sets the value of the formality property.
         * 
         */
        public void setFormality(int value) {
            this.formality = value;
        }

        /**
         * Gets the value of the generalGrade property.
         * 
         */
        public int getGeneralGrade() {
            return generalGrade;
        }

        /**
         * Sets the value of the generalGrade property.
         * 
         */
        public void setGeneralGrade(int value) {
            this.generalGrade = value;
        }

        /**
         * Gets the value of the references property.
         * 
         */
        public int getReferences() {
            return references;
        }

        /**
         * Sets the value of the references property.
         * 
         */
        public void setReferences(int value) {
            this.references = value;
        }

        /**
         * Gets the value of the headings property.
         * 
         */
        public int getHeadings() {
            return headings;
        }

        /**
         * Sets the value of the headings property.
         * 
         */
        public void setHeadings(int value) {
            this.headings = value;
        }

    }

}
